### ISSUE TITLE
Kill all the cheating functions

### ISSUE THREAD

**Issue by EagleEyeLogic** [KSP-RO/KCT#13]
Since we actually have to do some of the experiments with Kerbalism in small steps, we should somehow prevent all KCT cheating or replace it with meaningful functions.

1. The recovery costs money and time (depending on the distance from KSC).
2. Salvaged parts must be specially checked and refurbished.
3. If we recover parts via KCT Recovery, then of course we do not get extra money.

**Comment by EagleEyeLogic** [comment]
At home and now I'll try to explain what I meen.

Build a rocket early in Career, RD-100, Camera, etc. and an parashute in top torecover the whole vessel.
Build, roll it out, launch and the recover it using the KCT-SPH menu.
You will be paid like you where using the normal recovery button, but the parts you have recovered are on the way to your SPH.
If the rocket is in the SPH, use edit mode, change the orientation by 90 degrees, jump to the VAB and save the change. Now edit the rocket (it's now in the VAB) again. Ideally, you have recovered the entire rocket and only need to fill it up and roll it onto the Launchpad.
Time required about 9-12 days with a real construction time of 125-140 days. I am not sure how far away the rocket may be, but loose 1000km.

**Comment by lpgagnon** [comment]
You don't get "paid like you where using the normal recovery button"; the base game's recovery dialog _says_ it gives money back, but KCT doesn't let it happen.

As for 'do a SPH recovery then jump to VAB', yes, that's a cheat around the tech requirement for VAB recovery. A cheater could just as well just enable VAB recovery, though, so it doesn't seem like a "big" thing to me.

Interestingly, I think this will run afoul of a bug with that 'jump' button: the rocket will actually get deployed to the runway when launched.

**Comment by EagleEyeLogic** [comment]
No runway, the rocket is on the pad.
Problem ist not the cheater, it feels like the normal way.
