### ISSUE TITLE
In part edit mode there is no way to overwrite existing build plan

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/KCT#8]
That means the vessel has to be loaded into VAB as usual the next time and then the build plan entry can be overwritten with the updated vessel.

**Comment by linuxgurugamer** [comment]
Please open this on my fork, that is code I wrote
LGG

**Comment by Gordon-Dry** [comment]
Closed in favor for
https://github.com/linuxgurugamer/KCT/issues/15
