### ISSUE TITLE
Feature Request: UI Scaling

### ISSUE THREAD

**Issue by DocRockwell** [KSP-RO/KCT#9]
Would it be possible to get UI scaling for KCT? At high screen resolutions the text is very small, and throughout a game you'll spend a fair amount of time interacting with the KCT menus.

**Comment by siimav** [comment]
I think you might have a better chance of getting it implemented if you post the issue to LGG's fork. He's maintaining the version that gets served for stock players and that feature is probably something that even stock players would appreciate. This fork is mainly used for developing RP-1-specific functionality.

**Comment by DocRockwell** [comment]
Cheers, will do.

**Comment by linuxgurugamer** [comment]
He did, and I'll be looking at it this weekend
